version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=GraphQL
      - MYSQL_ROOT_PASSWORD=webservice
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  mon-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/GraphQL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: webservice
    depends_on:
      - db
volumes:
  db:
    driver: local